import type { Metadata } from "next";
import { Alegreya } from "next/font/google";
import "./globals.css";
import Navbar from "@/sections/navbar/Navbar";
import { ModalContextProvider } from "@/context/modal-context";
import Modal from "@/components/modal/Modal";

const alegreya = Alegreya({ 
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"] 

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={alegreya.className}>
        <ModalContextProvider>
          <div className="container">
            <Navbar />
            {children}
          </div>
          <Modal />
        </ModalContextProvider>
      </body>
    </html>
  );
}
